/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MoveItemJList.java
 *
 * Created on May 17, 2012, 7:24:51 PM
 */
package components;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Nga
 */
public class MoveItemJList extends javax.swing.JFrame {
    DefaultListModel listModel1;
    DefaultListModel listModel2;
    /** Creates new form MoveItemJList */
    public MoveItemJList() {
        initComponents();
        String[] s1 = {"xanh", "do", "tim", "vang"};
        String[] s2 = {"blue", "red", "magenta", "yellow"};
//        list1.setListData(s1);//list2.setListData(s2);
        listModel1 = new DefaultListModel();
        listModel2 = new DefaultListModel();
        for (int i = 0; i < s1.length; i++) {
            listModel1.add(i, s1[i]);
        }
        for (int i = 0; i < s2.length; i++) {
            listModel2.add(i, s2[i]);
        }
        list1.setModel(listModel1);
        list2.setModel(listModel2);
      //  list2 = new JList(listModel2); (khong new)
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList();
        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(list1);

        jScrollPane2.setViewportView(list2);

        btnLeft.setText("<<");
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        btnRight.setText(">>");
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnLeft)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRight)))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        // TODO add your handling code here:
        try {
            listModel1.addElement(list2.getSelectedValue());
            listModel2.remove(list2.getSelectedIndex());
        } catch (Exception e) {
            System.out.println("Khong chon hoac da het item: "+ e);
        }
    }//GEN-LAST:event_btnLeftActionPerformed
    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // TODO add your handling code here:
        try {
            listModel2.addElement(list1.getSelectedValue());
            listModel1.remove(list1.getSelectedIndex());
        } catch (Exception e) {
            System.out.println("Khong chon hoac da het item: "+ e);
        }
    }//GEN-LAST:event_btnRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MoveItemJList m = new MoveItemJList();
        m.setLocationRelativeTo(null);
        m.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList list1;
    private javax.swing.JList list2;
    // End of variables declaration//GEN-END:variables
}
