package components;

import java.awt.Color;
public class combox_list extends javax.swing.JFrame {

    /** Creates new form combox_list */
    public combox_list() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboDanhsach = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDanhsach = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboDanhsach.setFont(new java.awt.Font("Tahoma", 0, 18));
        cboDanhsach.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blue", "Green", "Magentta", "Yellow" }));
        cboDanhsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDanhsachActionPerformed(evt);
            }
        });

        lstDanhsach.setFont(new java.awt.Font("Tahoma", 0, 18));
        lstDanhsach.setForeground(new java.awt.Color(0, 51, 51));
        lstDanhsach.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Red", "Cyan", "Pink ", "Orange" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstDanhsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDanhsachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstDanhsach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(cboDanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboDanhsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDanhsachActionPerformed
        // TODO add your handling code here:
        //String x = cboDanhsach.getSelectedItem().toString();
        int hang = cboDanhsach.getSelectedIndex();
        if (hang == 0) {
            this.getContentPane().setBackground(Color.blue);
        } else if (hang == 1) {
            this.getContentPane().setBackground(Color.green);
        } else if (hang == 2) {
            this.getContentPane().setBackground(Color.magenta);
        } else if (hang == 3) {
            this.getContentPane().setBackground(Color.yellow);
        }
        //   JOptionPane.showMessageDialog(null,"ban vua click "+x,"Thong bao",
        //JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cboDanhsachActionPerformed

    private void lstDanhsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDanhsachMouseClicked
        // TODO add your handling code here:
        int hang = lstDanhsach.getSelectedIndex();
        if (hang == 0) {
            this.getContentPane().setBackground(Color.red);
        } else if (hang == 1) {
            this.getContentPane().setBackground(Color.cyan);
        } else if (hang == 2) {
            this.getContentPane().setBackground(Color.pink);
        } else if (hang == 3) {
            this.getContentPane().setBackground(Color.orange);
    }//GEN-LAST:event_lstDanhsachMouseClicked
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new combox_list().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboDanhsach;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstDanhsach;
    // End of variables declaration//GEN-END:variables
}
